package com.example.moviecatalogue;

import android.util.Log;

import java.util.ArrayList;

public class FilmData {
    public static String[][] data = new String[][]{
            {"A Star","Jackson Maine (Bradley Cooper), seorang penyanyi country terkenal yang berusaha melawan dirinya sendiri dari alkohol dan narkotika, tampil di sebuah konser di California. Dukungan utamanya adalah Bobby (Sam Elliott), kakak tiri sekaligus manajer Jackson. Setelah konser, Jackson mengunjungi sebuah kedai di mana ia melihat penampilan Ally (Lady Gaga), seorang pelayan sekaligus penyanyi dan penulis lagu. Jackson terkesan dengan penampilan Ally, lalu mereka menghabiskan malam bercerita satu sama lain ketika Ally memberitahu Jackson masalah yang dihadapinya dalam mengejar karier musik profesional.Jackson mengajak Ally ke konser Jackson selanjutnya. Meskipun ia menolak pada awalnya, Ally hadir dan dengan bantuan Jackson, ia tampil di panggung bersamanya. Jackson mengajak Ally untuk ikut tur dengannya dan mereka berhubungan romantis. Di Arizona, Ally dan Jackson mengunjungi peternakan tempat Jackson dibesarkan dan di mana ayahnya dimakamkan, namun Jackson terkejut mengetahui bahwa Bobby telah menjual tanah keluarga mereka. Marah dan merasa dikhianati, Jackson memukul Bobby, yang kemudian berhenti sebagai manajernya. Sebelum Bobby keluar, Bobby mengungkapkan bahwa ia sudah memberitahu Jackson tentang penjualan tanah tersebut beberapa waktu yang lalu, namun Jackson terlalu mabuk untuk memperhatikan penjelasan Bobby. ","https://m.media-amazon.com/images/M/MV5BNmE5ZmE3OGItNTdlNC00YmMxLWEzNjctYzAwOGQ5ODg0OTI0XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SY1000_CR0,0,666,1000_AL_.jpg","8.0"},

            {"Aquaman","In 1985 Maine, lighthouse keeper Thomas Curry rescues Atlanna, the princess of the underwater nation of Atlantis, during a storm. They eventually fall in love and have a son named Arthur, who is born with the power to communicate with marine lifeforms. Atlanna is forced to abandon her family and return to Atlantis, entrusting to her advisor, Nuidis Vulko, the mission of training Arthur. Under Vulko's guidance, Arthur becomes a skilled warrior but rejects Atlantis upon learning that Atlanna was executed for having a half-breed son. In the present, one year after Steppenwolf's invasion,[N 1] Arthur confronts a group of pirates attempting to hijack a Russian Naval nuclear submarine. Their leader, Jesse Kane, dies during the confrontation while his son, David, vows revenge. David later targets Atlantis at the behest of Orm, Arthur's younger half-brother and Atlantis' incumbent monarch who uses the attack as a pretext to declare war on the surface world. King Nereus of Xebel swears allegiance to Orm's cause, but his daughter Mera, who has been betrothed to Orm, refuses to aid them and journeys to the surface to ask Arthur for help, earning his trust by saving Thomas from a tsunami sent by Orm. Arthur reluctantly accompanies Mera to a rendezvous with Vulko, who urges Arthur to find the Trident of Atlan, a magic artifact that once belonged to Atlantis' first ruler, in order to reclaim his rightful place as king. They are ambushed by Orm's men and Mera and Vulko escape without having been seen, while Arthur is captured. ","https://m.media-amazon.com/images/M/MV5BOTk5ODg0OTU5M15BMl5BanBnXkFtZTgwMDQ3MDY3NjM@._V1_SY1000_CR0,0,674,1000_AL_.jpg","8.5"},

            {"Avenger Infinity","As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment, the fate of Earth and existence has never been more uncertain. Written by Marvel Studios","https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SY1000_CR0,0,674,1000_AL_.jpg","8.5"},

            {"Bird Box","In the wake of an unknown global terror, a mother must find the strength to flee with her children down a treacherous river in search of safety. Due to unseen deadly forces, the perilous journey must be made blindly. Directed by Emmy winner Susanne Bier, Bird Box is a thriller starring Academy Award winner Sandra Bullock, John Malkovich, Sarah Paulson, and Trevante Rhodes. Written by Netflix","https://m.media-amazon.com/images/M/MV5BMjAzMTI1MjMyN15BMl5BanBnXkFtZTgwNzU5MTE2NjM@._V1_SY1000_CR0,0,674,1000_AL_.jpg","7.5"},

            {"Bohemian Rhapsody","Bohemian Rhapsody is a foot-stomping celebration of Queen, their music and their extraordinary lead singer Freddie Mercury. Freddie defied stereotypes and shattered convention to become one of the most beloved entertainers on the planet. The film traces the meteoric rise of the band through their iconic songs and revolutionary sound. They reach unparalleled success, but in an unexpected turn Freddie, surrounded by darker influences, shuns Queen in pursuit of his solo career. Having suffered greatly without the collaboration of Queen, Freddie manages to reunite with his bandmates just in time for Live Aid. While bravely facing a recent AIDS diagnosis, Freddie leads the band in one of the greatest performances in the history of rock music. Queen cements a legacy that continues to inspire outsiders, dreamers and music lovers to this day. Written by Twentieth Century Fox","https://m.media-amazon.com/images/M/MV5BNDg2NjIxMDUyNF5BMl5BanBnXkFtZTgwMzEzNTE1NTM@._V1_SY1000_CR0,0,629,1000_AL_.jpg","7.0"},

            {"Bumblebee","On the run in the year 1987, Bumblebee finds refuge in a junkyard in a small Californian beach town. Charlie (Hailee Steinfeld), on the cusp of turning 18 and trying to find her place in the world, discovers Bumblebee, battle-scarred and broken. When Charlie revives him, she quickly learns this is no ordinary, yellow VW bug. Written by Paramount Pictures","https://m.media-amazon.com/images/M/MV5BOTM3NzE5OTE1Nl5BMl5BanBnXkFtZTgwNzQwNjM3NjM@._V1_SY1000_CR0,0,674,1000_AL_.jpg","7.5"},

            {"Creed II","Years after Adonis Creed made a name for himself under Rocky Balboa's mentorship, the young boxer becomes the Heavyweight Champion of the World. While life is good with that victory and his marriage to Bianca, trouble comes to Philadelphia when Ivan Drago, the Russian boxer who killed Adonis' father, Apollo, arrives with his son, Viktor, to challenge Adonis. Against Rocky's advice, Adonis accepts the challenge without his mentor's participation and pays the price in a punishing bout he wins only by a technicality. Now injured and demoralized, Adonis cannot bring himself to back into the game, leaving his spirit and title in jeopardy. Together, Adonis' family and Rocky must find a way to rekindle Adonis' fighting spirit to face the future in whatever choice he makes. Meanwhile, the Drago family have its own troubles trying to regain the respect in their homeland that they lost at Rocky's hands as they wonder whether is it truly worth it.","https://m.media-amazon.com/images/M/MV5BMTcxMjUwNjQ5N15BMl5BanBnXkFtZTgwNjk4MzI4NjM@._V1_.jpg","7.6"},

            {"Dead Pool","After losing Vanessa (Morena Baccarin), the love of his life, 4th-wall breaking mercenary Wade Wilson aka Deadpool (Ryan Reynolds) must assemble a team and protect a young, full-figured mutant Russell Collins aka Firefist (Julian Dennison) from Cable (Josh Brolin), a no-nonsense, dangerous cyborg from the future, and must also learn the most important lesson of all: to be part of a family again. Written by ahmetkozan","https://m.media-amazon.com/images/M/MV5BYzE5MjY1ZDgtMTkyNC00MTMyLThhMjAtZGI5OTE1NzFlZGJjXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY1000_CR0,0,666,1000_AL_.jpg","7.7"},

            {"Dragon","As Hiccup fulfills his dream of creating a peaceful dragon utopia, Toothless' discovery of an untamed, elusive mate draws the Night Fury away. When danger mounts at home and Hiccup's reign as village chief is tested, both dragon and rider must make impossible decisions to save their kind. Written by JC Jamison","https://m.media-amazon.com/images/M/MV5BMjIwMDIwNjAyOF5BMl5BanBnXkFtZTgwNDE1MDc2NTM@._V1_SY1000_CR0,0,631,1000_AL_.jpg","8.0"},

            {"Dragon Ball","Goku and Vegeta encounter Broly, a Saiyan warrior unlike any fighter they've faced before. ","https://m.media-amazon.com/images/M/MV5BMTg0YzM2NzMtOGM1OC00MzlkLWI1NDEtYTI2MGZkZGJlYWQ0XkEyXkFqcGdeQXVyNDQxNjcxNQ@@._V1_SY1000_CR0,0,715,1000_AL_.jpg","7.9"},

            {"Glass","After pursuing Kevin Wendell Crumb and the multiple identities that reside within. David Dunn finds himself locked in a mental hospital alongside his archenemy, Elijah Price and must contend with a psychiatrist who is out to prove the trio do not actually possess superhuman abilities Written by vsuperkuns","https://m.media-amazon.com/images/M/MV5BMTY1OTA2MjI5OV5BMl5BanBnXkFtZTgwNzkxMjU4NjM@._V1_SY1000_SX700_AL_.jpg","7.5"},

            {"Hunter Killer","A U.S. submarine, the USS Tampa Bay, vanishes while shadowing a Russian Akula-class submarine in the Arctic. Rear Admiral John Fisk sends a Virginia-class submarine, the USS Arkansas, under the command of newly-promoted and unorthodox Commander Joe Glass to investigate. At the same time, a Navy SEAL team under the command of Lieutenant Bill Beaman is sent in to discreetly observe a Russian naval base. When they arrive at the naval base, they witness defense minister Dmitri Durov conducting a coup d'etat and taking Russian President Zakarin prisoner, and swiftly realize that Durov intends to trigger a war..","https://m.media-amazon.com/images/M/MV5BYjRkNzQ0NmYtZmQyMS00Yzk5LWEzZjQtYzhlOTRlMzVjMzA3XkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SY1000_CR0,0,648,1000_AL_.jpg","7.0"},

            {"Marry Popins","In Depression-era London, a now-grown Jane and Michael Banks, along with Michael's three children, are visited by the enigmatic Mary Poppins following a personal loss. Through her unique magical skills, and with the aid of her friend Jack, she helps the family rediscover the joy and wonder missing in their lives. Written by Disney","https://m.media-amazon.com/images/M/MV5BMTk0NDIzMTA1MF5BMl5BanBnXkFtZTgwMzM0MTUzNjM@._V1_SY1000_SX675_AL_.jpg","7.5"},

            {"Mortal Engine","A mysterious young woman, Hester Shaw, emerges as the only one who can stop a giant, predator city on wheels devouring everything in its path. Feral, and fiercely driven by the memory of her mother, Hester joins forces with Tom Natsworthy, an outcast from London, along with Anna Fang, a dangerous outlaw with a bounty on her head.","https://m.media-amazon.com/images/M/MV5BNzY1MDA2OTQ0N15BMl5BanBnXkFtZTgwMTkzNjU2NTM@._V1_SY1000_CR0,0,631,1000_AL_.jpg","7.8"}
    };

    public static ArrayList<Film> getData() {
        ArrayList<Film> filmArrayList = new ArrayList<>();
        for (String[] aData : data) {
            Film film = new Film();
            film.setTitle(aData[0]);
            film.setDescribtion(aData[1]);
            film.setFoto(aData[2]);
            film.setRating(aData[3]);
            filmArrayList.add(film);
        }
        return filmArrayList;
    }
}
